server:
  port: 8080
  servlet:
    context-path: /app
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: never
    password: root
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_challenge_test
    username: root
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: ALWAYS
